export const recipeTags = [
  { Category_name: "肉料理", Hiragana_name: "にくりょうり" },
  { Category_name: "魚料理", Hiragana_name: "さかなりょうり" },
  { Category_name: "野菜", Hiragana_name: " やさい" },
  { Category_name: "おつまみ", Hiragana_name: "おつまみ" },
  { Category_name: "簡単", Hiragana_name: "かんたん" },
  { Category_name: "ダイエット", Hiragana_name: "だいえっと" },
  { Category_name: "ヘルシー", Hiragana_name: "へるしー" },
  { Category_name: "ご飯もの", Hiragana_name: "ごはんもの" },
  { Category_name: "サラダ", Hiragana_name: "さらだ" },
  { Category_name: "スープ", Hiragana_name: "すーぷ" },
  { Category_name: "味噌汁", Hiragana_name: "みそしる" },
  { Category_name: "パスタ", Hiragana_name: "ぱすた" },
  { Category_name: "麺類", Hiragana_name: "めんるい" },
  { Category_name: "温かい", Hiragana_name: "あたたかい" },
  { Category_name: "冷たい", Hiragana_name: "つめたい" },
  { Category_name: "韓国料理", Hiragana_name: "かんこくりょうり" },
  { Category_name: "中華料理", Hiragana_name: "ちゅうかりょうり" },
  { Category_name: "和食", Hiragana_name: "わしょく" },
  { Category_name: "イタリアン", Hiragana_name: "いたりあん" },
  { Category_name: "スペイン料理", Hiragana_name: "すぺいんりょうり" },
  { Category_name: "フレンチ", Hiragana_name: "ふれんち" },
  { Category_name: "辛い", Hiragana_name: "からい" },
  { Category_name: "甘い", Hiragana_name: "あまい" },
  { Category_name: "しょっぱい", Hiragana_name: "しょっぱい" },
  { Category_name: "子供に人気", Hiragana_name: "こどもににんき" },
  { Category_name: "作り置き", Hiragana_name: "つくりおき" },
  { Category_name: "お弁当", Hiragana_name: "おべんとう" },
  { Category_name: "春", Hiragana_name: "はる" },
  { Category_name: "夏", Hiragana_name: "なつ" },
  { Category_name: "秋", Hiragana_name: "あき" },
  { Category_name: "冬", Hiragana_name: "ふゆ" },
  { Category_name: "鍋料理", Hiragana_name: "なべりょうり" },
  { Category_name: "炒め物", Hiragana_name: "いためもの" },
  { Category_name: "揚げ物", Hiragana_name: "あげもの" },
  { Category_name: "蒸し料理", Hiragana_name: "むしりょうり" },
  { Category_name: "電子レンジ", Hiragana_name: "でんしれんじ" },
  { Category_name: "オーブン", Hiragana_name: "おーぶん" },
  { Category_name: "パン", Hiragana_name: "ぱん" },
  { Category_name: "離乳食", Hiragana_name: "りにゅうしょく" },
  { Category_name: "Cook Do", Hiragana_name: "くっくどぅ" },
  { Category_name: "手抜き料理", Hiragana_name: "てぬきりょうり" },
];
